# Generated by Django 5.2.13 on 2026-04-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse postale')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Matière')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Coefficient')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MedecinTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Médecin traitant',
                'verbose_name_plural': 'Médecins traitants',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lien', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur légal')], default='tuteur', max_length=20)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Note /20')),
                ('appreciation', models.TextField(blank=True, verbose_name='Appréciation')),
                ('trimestre', models.IntegerField(choices=[(1, '1er trimestre'), (2, '2e trimestre'), (3, '3e trimestre')], default=1, verbose_name='Trimestre')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.eleve', verbose_name='Élève')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['eleve', 'trimestre', 'matiere'],
            },
        ),
        migrations.AddField(
            model_name='eleve',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='eleves', to='eleves.parent', verbose_name='Parents / Tuteurs'),
        ),
        migrations.CreateModel(
            name='Sante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('habitudes_alimentaires', models.TextField(blank=True, verbose_name='Habitudes alimentaires')),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sante', to='eleves.eleve')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.medecintraitant', verbose_name='Médecin traitant')),
            ],
            options={
                'verbose_name': 'Données de santé',
                'verbose_name_plural': 'Données de santé',
            },
        ),
        migrations.CreateModel(
            name='Scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, max_length=20, verbose_name='Classe')),
                ('options', models.TextField(blank=True, verbose_name='Options choisies')),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scolarite', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Données scolaires',
                'verbose_name_plural': 'Données scolaires',
            },
        ),
    ]
