# Generated by Django 5.2.13 on 2026-04-22 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('scolarite', 'Scolarité'), ('professeur', 'Professeur'), ('vie_scolaire', 'Vie scolaire'), ('infirmier', 'Infirmier·ère'), ('cantine', 'Cantine'), ('eleve', 'Élève'), ('parent', 'Parent / Tuteur')], default='scolarite', max_length=20, verbose_name='Rôle')),
                ('classe', models.CharField(blank=True, max_length=50, verbose_name='Classe enseignée')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='eleves.eleve', verbose_name='Élève associé')),
                ('matieres', models.ManyToManyField(blank=True, to='eleves.matiere', verbose_name='Matières enseignées')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='eleves.parent', verbose_name='Parent associé')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
