# Generated by Django 5.2.13 on 2026-04-23 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_add_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('access', 'Accès'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('export', 'Export (portabilité)'), ('erase', 'Effacement (Art. 17)'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('breach_report', 'Signalement de violation')], max_length=20, verbose_name='Action')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='Cible')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BreachReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description de la violation suspectée')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('investigating', "En cours d'enquête"), ('resolved', 'Résolu'), ('dismissed', 'Classé sans suite')], default='pending', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administration')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breach_reports', to=settings.AUTH_USER_MODEL, verbose_name='Rapporteur')),
            ],
            options={
                'verbose_name': 'Signalement de violation',
                'verbose_name_plural': 'Signalements de violation',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
